name: nlpatient

channels:
  - conda-forge

dependencies:
  - python == 3.11
  - flask
  - flask-sqlalchemy
  - flask-cors
  - pyyaml
  - pymysql
  - cryptography
  - pytorch
  - scikit-learn
  - numpy
  - requests
  - pymongo
  - transformers
  - datasets
  - accelerate
